# Generated by Django 5.1.7 on 2025-04-24 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_clublocation_club_alter_clublocation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmeeting',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='clubs.club'),
        ),
    ]
