# Generated by Django 5.1.7 on 2026-07-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_clubmeeting_club'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clublocation',
            constraint=models.UniqueConstraint(fields=('club', 'location'), name='unique_location_for_club'),
        ),
    ]
