# Generated by Django 5.1.7 on 2025-03-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
