# Generated by Django 5.1.7 on 2025-04-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookrating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='name_placeholder', max_length=150),
            preserve_default=False,
        ),
    ]
