# Generated by Django 5.1.7 on 2025-04-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
