# Generated by Django 5.1.7 on 2025-04-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
