# Generated by Django 5.1.7 on 2025-04-09 19:06

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_year'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='books_autho_name_5aec2d_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='author_name_lower_idx'),
        ),
    ]
