# Generated by Django 5.1.7 on 2026-08-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_created_by_location_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_private',
            field=models.BooleanField(blank=True, default=True, help_text="Private locations (e.g. a member's home) have their address and access details redacted once the creator leaves the club."),
        ),
    ]
