# Generated by Django 5.1.7 on 2025-03-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
