# Generated by Django 5.1.7 on 2025-03-22 15:03

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookrating_comment'),
        ('clubs', '0004_alter_club_description_alter_club_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglistitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='readinglistitem',
            constraint=models.UniqueConstraint(fields=('reading_list', 'book'), name='unique_book_in_reading_list'),
        ),
    ]
