# Generated by Django 5.1.7 on 2025-04-03 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_readinglistitem_created_at_and_more'),
        ('locations', '0002_alter_location_access_details_alter_location_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='clubs.club')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
    ]
