# Generated by Django 5.1.7 on 2025-04-09 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_clublocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglistitem',
            name='reading_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list_items', to='clubs.readinglist'),
        ),
    ]
